throw (succ (0))
succ (0)
0
try
{
  fail (n)
}
catch
{
  a => true
}
true
fail (n)
n
fail
